language: python
addons:
  postgresql: "9.2"
  firefox: "latest-esr"
services:
  - postgresql
python:
  - "3.5"
before_install:
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz"
  - "mkdir geckodriver"
  - "tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver"
  - "export PATH=$PATH:$PWD/geckodriver"
install:
  - "pip install -r requirements.txt"
before_script:
  - "psql -c 'CREATE ROLE django WITH LOGIN CREATEDB;' -U postgres"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start
script:
  - "./wsgi/cnto/manage.py behave wsgi/cnto/features"
